### PR TITLE
2021.3.31.3s Support

### PR DESCRIPTION
**Pull request by ghost**
Adds Support for 2021.3.31.3s, which is the Latest Airship Patch. BepInEx version used is Latest Reactor fork.

### CODE REVIEW

**Comment by ghost** [comment]
Enclosed is a 1.0.2 release which also resizes the hat size in the hat tab, will update PR with updated code
[CorsacHats-1.0.2.zip](https://github.com/kiraacorsac/CorsacHats/files/6274127/CorsacHats-1.0.2.zip)

**Comment by kiraacorsac** [comment]
Oooooh, I didn't notice this. I also don't really have time to try it out right now. I quickly scanned over the files and they seem OK.

**Comment by ghost** [comment]
> Oooooh, I didn't notice this. I also don't really have time to try it out right now. I quickly scanned over the files and they seem OK.

I have a fork over on my Repos that's up to date with the latest update, if you wanna update to that, feel free to update your code. I'll be trying to keep it as up to date as possible, as well as adding new features in future :)

**Comment by amsryq** [comment]
Wow this got merged, gotta update it again rn XD

**Comment by ghost** [comment]
> Wow this got merged, gotta update it again rn XD

latest update on my repo already works on the latest update, however I’m gonna rewrite the implementation as the newer updates screwed things.

**Comment by amsryq** [comment]
> latest update on my repo already works on the latest update, however I’m gonna rewrite the implementation as the newer updates screwed things.

It doesn't really screwed anything, just change the scale and it'll work

image

**Comment by ghost** [comment]
> > latest update on my repo already works on the latest update, however I’m gonna rewrite the implementation as the newer updates screwed things.
> 
> It doesn't really screwed anything, just change the scale and it'll work
> 
> image

Its not the image scale, but the initial Airship update Implemented a few changes I wanna include in the source, like Ladder climb animations etc, which CorsacHats Doesn't do. 

Edit: Doesn't for me. Might for others, but anything I do is null when the new animations come into play.

**Pull request merged**
